version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.6
  ansible-playbook: orbss/ansible-playbook@0.0.5
  ruby: circleci/ruby@1.2.0

jobs: 
  cloudformation-execute:
    executor: aws-cli/default
    environment:
      STACK_NAME: sample-stack
      TEMPLATE_FILE: CFn_template/service.yml
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run:
          name: Excute Create/Update Stack
          command: |
            aws cloudformation deploy --stack-name $STACK_NAME --template-file $TEMPLATE_FILE

  ansible-execute:
    executor: ansible-playbook/default
    steps:
      - checkout
      - add_ssh_keys:  
          fingerprints:  
            - "28:b8:76:c9:49:07:76:4e:d2:15:90:76:e6:ae:08:ea"
      - ansible-playbook/install:
          version: "2.9.23"
      - ansible-playbook/playbook:
          inventory: "ANSIBLE_INVENTORY"
          playbook: "ansible/playbook.yml"
          playbook-options: "-u ec2-user"
          
  serverspec-execute:
    executor: ruby/default
    steps:
      - checkout
      - add_ssh_keys:  
          fingerprints:  
            - "28:b8:76:c9:49:07:76:4e:d2:15:90:76:e6:ae:08:ea" 
      - ruby/install:
          version: "3.1.1"
      - run:
          name: "Install serverspec"
          command: |
            gem install serverspec
      - run:
          name: "Execute serverspec"
          command: |
            rspec  
            
  
workflows:
  sample-workflow:
    jobs:
      - cloudformation-execute
      - ansible-execute:
          requires:
            - cloudformation-execute
      - serverspec-execute:
          requires:
            - cloudformation-execute
            - ansible-execute
